name: GreenMinecraft
version: '${project.version}'
main: greenminecraft.greenminecraft.GreenMinecraft
api-version: 1.19
authors: [ Steven ]
description: Adding green to minecraft
website: https://github.com/sjiforgot/green-minecraft
